# Generated by Django 5.0.3 on 2024-03-24 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0005_remove_uploadedimagetweet_tweet'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UploadedImageTweet',
        ),
    ]
