# Generated by Django 5.0.3 on 2024-03-24 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0007_uploadedimagetweet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadedimagetweet',
            name='file',
            field=models.FileField(upload_to='imagetweet/'),
        ),
    ]
