# Generated by Django 5.0.3 on 2024-03-24 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0008_alter_uploadedimagetweet_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadedimagetweet',
            name='file',
            field=models.ImageField(upload_to='imagetweet/'),
        ),
    ]
