# Generated by Django 5.0.3 on 2024-05-02 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0023_rename_reportuser_report'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
