# Generated by Django 5.0.3 on 2024-05-23 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0033_salebook'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SaleBook',
        ),
    ]
