# Generated by Django 5.0.3 on 2024-05-23 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0037_salebook'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salebook',
            name='price',
        ),
        migrations.AlterField(
            model_name='salebook',
            name='print_year',
            field=models.PositiveSmallIntegerField(),
        ),
    ]
