# Generated by Django 5.0.3 on 2024-05-23 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0040_salebook'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salebook',
            name='print_year',
            field=models.PositiveIntegerField(),
        ),
    ]
