# Generated by Django 5.0.3 on 2024-05-23 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0041_alter_salebook_print_year'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SaleBook',
        ),
    ]
