# Generated by Django 5.0.3 on 2024-06-13 13:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0043_salebook'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BookVote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bvote', to='book.salebook')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ubvote', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
