# Generated by Django 5.0.3 on 2024-07-03 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0046_bookcommentvote'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BookCommentVote',
        ),
    ]
