# Generated by Django 5.0.3 on 2024-07-03 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0048_bookcommentvote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookcommentvote',
            name='Like_or_DisLike',
            field=models.CharField(),
        ),
    ]
