# Generated by Django 5.0.3 on 2024-07-03 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0049_alter_bookcommentvote_like_or_dislike'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookcommentvote',
            name='Like_or_DisLike',
            field=models.CharField(choices=[('like', 'Like'), ('dislike', ' Dislike')]),
        ),
    ]
