# Generated by Django 5.0.3 on 2024-07-03 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0050_alter_bookcommentvote_like_or_dislike'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BookCommentVote',
        ),
    ]
