# Generated by Django 5.0.3 on 2024-07-03 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0052_bookcommentdislike_bookcommentlike'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CommentVote',
        ),
    ]
