# Generated by Django 5.0.3 on 2024-07-04 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0055_recommendedbookuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RecommendedBookUser',
        ),
    ]
