# Generated by Django 5.0.3 on 2024-07-04 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0057_recommendedbookuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recommendedbookuser',
            name='author',
            field=models.CharField(),
        ),
    ]
