# Generated by Django 5.0.3 on 2024-07-06 09:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0058_alter_recommendedbookuser_author'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistrationRequestedBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_book', models.CharField()),
                ('author', models.CharField()),
                ('print_year', models.CharField(blank=True, max_length=4, null=True)),
                ('category', models.CharField()),
                ('Description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ubook', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
