# Generated by Django 5.0.3 on 2024-07-06 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0059_registrationrequestedbook'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrationrequestedbook',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
