# Generated by Django 5.0.3 on 2024-07-10 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0061_dontshownotificationregistrationrequestedbook'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DontShowNotificationRegistrationRequestedBook',
        ),
    ]
