# Generated by Django 5.0.3 on 2024-07-16 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0065_alter_cart_book_alter_cart_user_factor'),
    ]

    operations = [
        migrations.AddField(
            model_name='factor',
            name='show',
            field=models.BooleanField(default=False),
        ),
    ]
