# Generated by Django 5.0.3 on 2024-07-17 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0066_factor_show'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='factor',
            name='show',
        ),
    ]
